name: Publish packages

on: [workflow_dispatch]

jobs:
  Publish-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: "Update Packages"
        env:
           NODE_AUTH_TOKEN: 'EXAMPLE_TOKEN'
        run: |
          echo 'Hello Action!'
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          git status
          git branch -l
          echo 'Bye!'
      - name: Message success
        if: success()
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Publish packages succeeded! ✅',
            });
      - name: Message failure
        if: failure()
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Publish packages failed! ❌',
            });
