name: Publish packages

on:
 issue_comment:
   types: [created, edited]

jobs:
  Publish-packages:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: "Update Packages"
        env:
           NODE_AUTH_TOKEN: 'EXAMPLE_TOKEN'
        if: contains(github.event.comment.body, 'Publish package')
        run: |
          echo 'Hello Action'
          echo ${{ github.ref }}
      - name: Message success
        if: ${{ success() && contains(github.event.comment.body, 'Publish package') }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Publish packages succeeded! ✅',
            });
      - name: Message failure
        if: ${{ failure() && contains(github.event.comment.body, 'Publish package') }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Publish packages failed! ❌',
            });
